# Site settings
title: Stefan Bischof - Knowledge Graph Researcher
email: stefan@stefanbischof.at
description: > # this means to ignore newlines until "baseurl:"
  Research scientist at Siemens AG Ã–sterreich. External lecturer at FH Krems. interested in (Industrial) Knowledge Graphs and semantic modelling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.stefanbischof.at" # the base hostname & protocol for your site
github_username:  stefanbischof
author:
  name: Stefan Bischof
social:
  name: Stefan Bischof
  links:
    - https://github.com/stefanbischof
    - https://linkedin.com/in/stefanbischof
    - https://dblp.org/pid/40/3609-2.html
    - https://scholar.google.com/citations?user=U8wSrHwAAAAJ
    - https://orcid.org/0000-0001-9521-8907
    - https://www.scopus.com/authid/detail.uri?authorId=6701506511
    - https://www.semanticscholar.org/author/Stefan-Bischof/143877076
webmaster_verifications:
  google: uCs0oiMeUVzn9UBXLcNZXLddVbmM7oOy408K8tzeFbw

include: [".well-known"]

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Stefan Bischof"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

collections:
  doc:
    output: true
  publications:
    output: true
    permalink: /publications/:name/

sass:
    style: compressed
